In [1]:
import pandas as pd
import yfinance as yf

In [11]:
ticker = "ESRS.CA"

# Download historical data (daily OHLCV)
df_raw = yf.download(ticker, start='2018-01-01')
df_raw.columns = df_raw.columns.get_level_values(0)

print(df_raw.head())

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open  Volume
Date
2018-01-01  18.226999  18.226999  18.226999  18.226999       0
2018-01-02  18.226999  18.226999  18.226999  18.226999       0
2018-01-03  18.034119  18.411108  17.920146  18.297135   32998
2018-01-04  17.543158  18.034120  17.183703  18.034120  182655
2018-01-07  17.543158  17.543158  17.543158  17.543158       0

In [12]:
df_raw

Price            Close        High         Low        Open  Volume
Date
2018-01-01   18.226999   18.226999   18.226999   18.226999       0
2018-01-02   18.226999   18.226999   18.226999   18.226999       0
2018-01-03   18.034119   18.411108   17.920146   18.297135   32998
2018-01-04   17.543158   18.034120   17.183703   18.034120  182655
2018-01-07   17.543158   17.543158   17.543158   17.543158       0
...                ...         ...         ...         ...     ...
2025-03-09  138.149994  138.000000  134.009995  138.149994    1797
2025-03-10  133.899994  137.899994  131.000000  138.149994    8099
2025-03-11  133.899994  136.149994  133.899994  133.899994    1947
2025-03-12  133.899994  135.899994  134.149994  133.899994    1352
2025-03-13  133.899994  133.899994  133.899994  133.899994       0

[1780 rows x 5 columns]

In [ ]:
df_raw.to_csv("orwe_data_raw.csv")

# Feature engineering

In [13]:
df = df_raw

In [15]:
#Price based features
df['return_1d'] = df['Close'].pct_change()
df['return_5d'] = df['Close'].pct_change(5)
df['return_10d'] = df['Close'].pct_change(10)

#Trend indicators
df['ma_10'] = df['Close'].rolling(10).mean()
df['ma_50'] = df['Close'].rolling(50).mean()

#Relative postion to trend
df['ma_ratio_10'] = df['Close'] / df['ma_10']
df['ma_ratio_50'] = df['Close'] / df['ma_50']

#RSI indicator
delta = df['Close'].diff()

gain = (delta.where(delta > 0, 0)).rolling(14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(14).mean()

rs = gain / loss
df['rsi'] = 100 - (100 / (1 + rs))

#MACD indicator
ema_12 = df['Close'].ewm(span=12, adjust=False).mean()
ema_26 = df['Close'].ewm(span=26, adjust=False).mean()

df['macd'] = ema_12 - ema_26
df['macd_signal'] = df['macd'].ewm(span=9, adjust=False).mean()
df['macd_hist'] = df['macd'] - df['macd_signal']

#Volatility
df['volatility_10'] = df['Close'].pct_change().rolling(10).std()
df['volatility_20'] = df['Close'].pct_change().rolling(20).std()

#Volume based features
df['volume_avg_10'] = df['Volume'].rolling(10).mean()
df['volume_ratio'] = df['Volume'] / df['volume_avg_10']

In [17]:
df['target'] = (df['Close'].shift(-1) > df['Close']).astype(int)
#df['targe_price'] = df['Close'].shift(-1)

In [19]:
df.dropna(inplace=True)

#Days with zero volume are holidays so we can remove them
df = df[df['Volume'] != 0]

In [20]:
df

Price,Close,High,Low,Open,Volume,return_1d,return_5d,return_10d,ma_10,ma_50,...,ma_ratio_50,rsi,macd,macd_signal,macd_hist,volatility_10,volatility_20,volume_avg_10,volume_ratio,target
Date,,,,,,,,,,,,,,,,,,,,,
2018-03-11,21.891685,22.163470,21.567300,21.979358,529709,0.015453,0.044770,0.041284,21.112283,19.999725,...,1.094599,49.223608,0.401205,0.374039,0.027165,0.018596,0.026364,937160.2,0.565228,1
2018-03-12,22.338814,22.663201,21.935524,21.891687,2648567,0.020425,0.073746,0.076013,21.270092,20.081962,...,1.112382,52.949658,0.462250,0.391681,0.070569,0.018218,0.025211,1182124.9,2.240514,0
2018-03-13,22.031960,22.417717,21.681272,22.338812,5396744,-0.013736,0.046211,0.073473,21.420888,20.158061,...,1.092960,65.248200,0.480331,0.409411,0.070920,0.018500,0.023833,1574285.1,3.428060,1
2018-03-14,22.540459,22.733338,22.102099,22.031961,2808189,0.023080,0.045547,0.094043,21.614643,20.248188,...,1.113209,72.572390,0.529588,0.433447,0.096141,0.019095,0.024256,1753287.5,1.601671,0
2018-03-15,22.444021,22.619364,22.137169,22.540459,1946328,-0.004278,0.041074,0.048321,21.718096,20.346205,...,1.103106,66.007925,0.554451,0.457647,0.096803,0.016252,0.023801,1713165.9,1.136100,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-03-06,138.440002,140.000000,133.250000,135.580002,15086,0.021095,0.009921,0.017941,136.922000,128.703400,...,1.075651,75.593997,2.385060,2.730476,-0.345417,0.008232,0.007365,224830.6,0.067099,0
2025-03-09,138.149994,138.000000,134.009995,138.149994,1797,-0.002095,0.007438,0.012088,137.087000,129.301999,...,1.068429,70.890358,2.345218,2.653425,-0.308207,0.008289,0.006791,86814.4,0.020699,0
2025-03-10,133.899994,137.899994,131.000000,138.149994,8099,-0.030764,-0.023768,-0.019048,136.826999,129.801999,...,1.031571,44.489771,1.948246,2.512389,-0.564143,0.013106,0.010054,52825.3,0.153317,0
2025-03-11,133.899994,136.149994,133.899994,133.899994,1947,0.000000,-0.024834,-0.021914,136.526999,130.253799,...,1.027993,45.416641,1.615025,2.332916,-0.717891,0.013020,0.010054,14422.2,0.135000,0
2025-03-12,133.899994,135.899994,134.149994,133.899994,1352,0.000000,-0.012391,-0.019909,136.254999,130.682199,...,1.024623,40.454518,1.335550,2.133443,-0.797893,0.013038,0.009517,13338.2,0.101363,0

In [ ]:
df.columns

In [9]:
df.to_csv("ESRS_features_data.csv")